### ISSUE TITLE
colors for other survey bands?

### ISSUE THREAD

**Issue by aureliocarnero** [DarkEnergySurvey/descolors#2]
Hello, I would like to expand the color palete to other filters, like VHS (J,H,Ks) or WISE (w1,w2,w3,w4). 
Could you please help me choosing colors that are suitable for thricomatic and color blind? And maybe, these could be add to this library

**Comment by kadrlica** [comment]
To choose colors that are colorblind accessible we used [this website](http://www.color-blindness.com/coblis-color-blindness-simulator/). 

You might experiment with these recommended colors from http://jfly.iam.u-tokyo.ac.jp/color/
```
colors = ["#000000", "#E69F00", "#56B4E9", "#009E73", "#F0E442", "#0072B2", "#D55E00", "#CC79A7"]
```

Or this color palette from tableau:
```
import palettable
colors = palettable.tableau.ColorBlind_10.mpl_colors
```

Since I don't think that we can generically satisfy the 3 criteria for the DES filter color scheme with the bands from other telescopes, I think that we would not include a recommendation for VHS or WISE here.
